const { GoogleGenerativeAI } = require('@google/generative-ai');

/**
 * Service for interacting with the Gemini AI API for script and metadata generation.
 */
class AIService {
  /**
   * @param {Object} config - System configuration.
   */
  constructor(config) {
    this.genAI = new GoogleGenerativeAI(config.geminiApiKey);
    this.model = this.genAI.getGenerativeModel({ model: "gemini-1.5-flash" });
  }

  /**
   * Generates a video script based on source content and source type.
   * @param {string|string[]} payload - Source text content.
   * @param {string} sourceType - 'DOC' or 'RESEARCH'.
   * @returns {Promise<string>} The generated script.
   */
  async generateScript(payload, sourceType) {
    const contentString = Array.isArray(payload) ? payload.join('\n') : payload;
    const prompt = sourceType === 'DOC' 
      ? `Transform the following document content into a YouTube video script for a virtual avatar. Use [HAPPY], [SAD], [ANGRY], [SURPRISED] expression tags at the start of each line. Keep it engaging.\n\nContent:\n${contentString}`
      : `Research findings:\n${contentString}\n\nBased on these findings, write a compelling YouTube video script for a virtual avatar. Use [HAPPY], [SAD], [ANGRY], [SURPRISED] expression tags for delivery.`;

    const result = await this._callWithRetry(async () => {
      const response = await this.model.generateContent(prompt);
      return response.response.text();
    });

    return result;
  }

  /**
   * Analyzes a script to generate video metadata and thumbnail design hints.
   * @param {string} script - The generated script.
   * @param {string} sourceType - 'DOC' or 'RESEARCH'.
   * @returns {Promise<Object>} Metadata and thumbnail data.
   */
  async generateVideoData(script, sourceType) {
    const prompt = `Analyze this video script and return a JSON object with:
    {
      "metadata": { "title": "...", "description": "...", "hashtags": ["...", "..."] },
      "thumbnail": { "theme": "...", "twoWordTitle": "...", "characterPose": "...", "accentHex": "..." }
    }
    
    Script:\n${script}`;

    const result = await this._callWithRetry(async () => {
      const response = await this.model.generateContent(prompt);
      const text = response.response.text();
      try {
        // Basic extraction if AI wraps in code blocks
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        return JSON.parse(jsonMatch ? jsonMatch[0] : text);
      } catch (e) {
        console.warn('AI returned malformed JSON, retrying...');
        return null;
      }
    });

    return result || {
      metadata: { title: 'New Video', description: 'Generated by autoConMan', hashtags: ['AI', sourceType] },
      thumbnail: { theme: 'DEFAULT', twoWordTitle: 'BREAKING NEWS', characterPose: 'IDLE', accentHex: '#7C4DFF' }
    };
  }

  /**
   * Retries an async function with exponential backoff on failure.
   * @private
   * @param {Function} fn - Async function to call.
   * @param {number} [retries=3] - Max retries.
   * @returns {Promise<any>}
   */
  async _callWithRetry(fn, retries = 3) {
    for (let i = 0; i < retries; i++) {
      try {
        const result = await fn();
        if (result !== null) return result;
      } catch (error) {
        if (i === retries - 1) throw error;
        const delay = Math.pow(2, i) * 1000;
        console.warn(`AI request failed, retrying in ${delay / 1000}s... (Error: ${error.message})`);
        await new Promise(r => setTimeout(r, delay));
      }
    }
  }
}

module.exports = AIService;
